### ISSUE TITLE
Run clean without private repo access

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#100]
Currently we have some private repos in `repository-list.txt`:

cerc-io/ipld-eth-beacon-indexer
cerc-io/ipld-eth-beacon-db
vulcanize/uniswap-watcher-ts
cerc-io/eth-probe

**Comment by zramsay** [comment]
this works out of the box (without perms) with the latest release:
`./laconic-so --verbose setup-repositories --exclude vulcanize/ops,vulcanize/ipld-eth-beacon-indexer,vulcanize/ipld-eth-beacon-db`

**Comment by zramsay** [comment]
i stand corrected and confused. Tried again on a fresh instance:
`./laconic-so --verbose setup-repositories --exclude vulcanize/ops,cerc-io/ipld-eth-beacon-indexer,cerc-io/ipld-eth-beacon-db,vulcanize/uniswap-watcher-ts,cerc-io/eth-probe`

**Comment by dboreham** [comment]
This works for me:

```
./laconic-so --verbose setup-repositories --exclude cerc-io/ipld-eth-beacon-indexer,cerc-io/ipld-eth-beacon-db,vulcanize/uniswap-watcher-ts,cerc-io/eth-probe
```

**Comment by dboreham** [comment]
setup-repositories doesn't depend on Docker.

**Comment by zramsay** [comment]
running different binaries, my bad

**Comment by zramsay** [comment]
going back to the original issue, can we do something like: `repository-list.csv` where
```
org/public-repo,true
org,private-repo,false
...
org/public-repo-not-needed,false
```
such that the default behaviour of running:
```
laconic-so setup-repositories
laconic-so build-containers
laconic-so deploy-system
```
is the simplest fixture for demo'ing an erc20 watcher? ... given that 99% of prod use cases for SO will be custom

**Comment by dboreham** [comment]
Kind of. We have this "stack" concept that allows the set of repos for some given goal (like "deploy an ERC20 watcher") to be defined. So eventually we won't have a scenario where the goal is "fetch all repos", and the only scenario under which private repos would be fetched would be when the goal is "do something involving private repos".

So the user would run something like:

```
laconic-so stack erc20watcher --token-name FOOCOIN up
```

```

**Comment by zramsay** [comment]
ah ok that makes a lot of sense, seems like that eventuality will make #106 more or less moot

**Comment by dboreham** [comment]
I think we can mark this fixed now since a) most of the repos are now public, and b) we have `--stack <my-stack>` implemented so will no longer need to pull all repos or come up with a magic mix of repos.

Still to do: update docs so users are not typing commands without `--stack`.
