### ISSUE TITLE
deploy-system fails

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#109]
From @rickmanelius :

So I tried this again with the [v1.0.5-alpha](https://github.com/cerc-io/stack-orchestrator/releases/tag/v1.0.5-alpha) release and [the updated docs you provided last night](http://docs-staging.laconic.com/docs/tutorials/quick-start/). Now I'm getting stuck at the stack stand-up step because of a Python error.

```
  File "/Users/rickmanelius/.shiv/laconic-so_23bc390eae8bbd8a4216b226b4454edf233fa21431364bc1495796b58a35e576/site-packages/app/deploy_system.py", line 44, in command
    compose_dir = Path(__file__).absolute().parent.joinpath("data", "compose")
NameError: name 'Path' is not defined. Did you mean: 'path'?
```

It looks like we didn't import the `Path` module needed here https://github.com/cerc-io/stack-orchestrator/blob/main/app/deploy_system.py#L44.

Looks like we might need `from pathlib import Path`

**Comment by rickmanelius** [comment]
@dboreham Thanks for cutting out a new issue.

I will still keep https://github.com/cerc-io/stack-orchestrator/issues/3 open as a meta ticket to resolve all other factors to get to a successful build on macOS 🙏🏻

**Comment by dboreham** [comment]
> @dboreham Thanks for cutting out a new issue.
> 
> I will still keep #3 open as a meta ticket to resolve all other factors to get to a successful build on macOS 🙏🏻

That's not what that issue is fwiw. It's about a very specific instance of something not working on macos.

Feel free to open a new tracking issue for the purpose of keeping track of all macos issues though.

**Comment by dboreham** [comment]
Turns out this isn't macos specific.

**Comment by dboreham** [comment]
Fixed in: https://github.com/cerc-io/stack-orchestrator/pull/108
