### ISSUE TITLE
Make the shiv distributable self-updating

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#11]
e.g. like this tool does: https://sdkman.io/ (it's shell script, so we can't directly copy their approach).

**Comment by ABastionOfSanity** [comment]
A --version arg would also be useful and probably goes hand in hand with a self-update function.

**Comment by zramsay** [comment]
+1 for a `--version` arg`

**Comment by dboreham** [comment]
> +1 for a `--version` arg`

https://github.com/cerc-io/stack-orchestrator/issues/101

**Comment by dboreham** [comment]
Done: https://github.com/cerc-io/stack-orchestrator/pull/545
