### ISSUE TITLE
Failure on CentOS

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#126]
From Alex H:

we ran into snags in a CentOS environment, BTW, minor stuff, but CentOS has both Python2 (/usr/bin/python) and Python3 (/usr/bin/python3) and it was failing as a result

**Comment by dboreham** [comment]
I tried to reproduce on a CentOS 9 VM but it worked:

```
[david@centos-test-1 ~]$ ./laconic-so
Usage: python -m laconic-so [OPTIONS] COMMAND [ARGS]...

  Laconic Stack Orchestrator

Options:
  --quiet
  --verbose
  --dry-run
  --local-stack
  --debug
  -h, --help     Show this message and exit.

Commands:
  build-containers    build the set of containers required for a complete...
  build-npms          build the set of npm packages required for a...
  deploy-system       deploy a stack
  setup-repositories  git clone the set of repositories required to build...
  version             print tool version
[david@centos-test-1 ~]$ cat /etc/redhat-release
CentOS Stream release 9
```

**Comment by dboreham** [comment]
btw this was a stock VM at Digitalocean. I did have to install git, but otherwise no special packages were installed.

**Comment by zramsay** [comment]
on a mac (just discovered I still have python 2) this isn't a problem:
```
$ which python
/usr/local/bin/python
$ which python3
/usr/local/bin/python3
```

**Comment by dboreham** [comment]
Just to confuse things more: /usr/local/bin/python could also be Python3. But none of that matters because stack-orchestrator explicitly runs python3 always.

**Comment by dboreham** [comment]
Since we haven't heard more about this in a while, closing as works for me.
