### ISSUE TITLE
Automate package publication

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#141]
Currently the shiv package is built and published manually.
Automate this in jenkins.
Find a place that isn't github to publish? Keep publishing to github for now?

**Comment by AFDudley** [comment]
Please publish to both github and gitea for the time being, thanks.

**Comment by dboreham** [comment]
gitea generic package repository doc: https://docs.gitea.io/en-us/packages/generic/

**Comment by dboreham** [comment]
doc on publishing to github: https://docs.github.com/en/rest/releases?apiVersion=2022-11-28

Hopefully we can find some tool that avoids the need to deal directly with their API.

**Comment by dboreham** [comment]
https://github.com/pgdurand/github-release-api

**Comment by dboreham** [comment]
Done for github.
