### ISSUE TITLE
Update and document `--branches-file`

### ISSUE THREAD

**Issue by zramsay** [cerc-io/stack-orchestrator#142]
I was thinking about full stack integration tests and how close SO is to being able to do this. My idea was:

```
laconic-so ---include cerc-io/laconicd:<commit/tag/branch> setup-repositories
```

then discovered this functionality already exists but needs updating. IMO it should be flexible for commit/tag/branch, such that when testing some bug fix for repo A, which relies on updates to repo B and C, the user can run something like:

```
laconic-so --branches-file branches.csv setup-repositories
```

where `branches.csv` can look like:

 ```
 cerc-io/laconic-sdk:commit
 cerc-io/laconicd:branch
 cerc-io/laconic-registry-cli:tag
 ```
 
 This is a current problem, e.g., these bugs all appear related
 https://github.com/cerc-io/laconic-sdk/issues/7
 https://github.com/cerc-io/laconic-sdk/issues/22
 https://github.com/cerc-io/laconic-registry-cli/issues/17
 https://github.com/cerc-io/laconic-registry-cli/issues/18
 
 and possibly fixed by: https://github.com/cerc-io/laconicd/pull/86
 
but it's currently an unnecessary lift to test, compounded by stuff like: https://github.com/cerc-io/laconicd/issues/82#issuecomment-1387230701

Being able to 1) edit the `branches.csv` then 2) run that one-liner (plus build-containers/deploy-system) would be :chefskiss:

**Comment by dboreham** [comment]
branches-file was a bit of a temporary hack. It may be better to integrate branch specification into `stack.yml` now we have that?

**Comment by dboreham** [comment]
Addressed in : https://github.com/cerc-io/stack-orchestrator/pull/409
