### ISSUE TITLE
Explain how S-O uses Docker and implement a sanity check that checks the min required Docker version is installed

### ISSUE THREAD

**Issue by zramsay** [cerc-io/stack-orchestrator#146]
from #125:
The tool really requires some basic understanding of Docker principles. Although the tool implements an abstraction layer over Docker and compose, it's not reasonable to expect anything beyond blind following of a tutorial to result in success without some basic level of insight into what's happening underneath. We should note this and point readers to some good Docker background doc or YouTube video where they can get up to speed if needed.

- [ ] section in README that links to...
- [ ] docs/DOCKER.md
- [ ] Docker Desktop is great (has both docker/docker-compose) but for cloud/scripting there's the plugin stuff to explain
- [ ] you never really have to install `docker`; it either comes with DD or is also installed by `apt install docker-compose`

**Comment by dboreham** [comment]
Testing github string length limits there :)

**Comment by zramsay** [comment]
we have install scripts that work great
