### ISSUE TITLE
Build cerc/fixturenet-eth-lighthouse from source

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#148]
Currently this image won't build on aarm64 because one of the base images isn't published for that architecture. But we shouldn't be pulling lighthouse pre-built from a docker hub image anyway, so let's instead build it from source which will fix both problems.

**Comment by dboreham** [comment]
This doesn't work because the base image: `sigp/lcli:v3.2.1` is not published for aarm64.
We get the Lighthouse cli tool `lcli` from that image.
`lcli` is not shipped in the main Lighthouse image (which does have an aarm64 build).

While building both Lighthouse images from source would solve this problem, it also takes a long time (Rust...) 
so perhaps we should look at only building where necessary. This would require us to create some sort of 
conditional dependency building mechanism.

**Comment by dboreham** [comment]
This may be as simple as us building the `sigp/lcli` image -- it doesn't seem to have any weird ARM incompatibilities.

**Comment by roysc** [comment]
@dboreham that's been working for me.

**Comment by dboreham** [comment]
We now build the lcli container from source.
