### ISSUE TITLE
Build cerc/go-ethereum-foundry from source

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#149]
This container doesn't build on aarm64 because the base images isn't published for that architecture. 
We should build it from source.

```
$ laconic-so build-containers --include cerc/go-ethereum-foundry
Dev Root is: /home/david/cerc
Building: cerc/go-ethereum-foundry
Sending build context to Docker daemon  87.04kB
Step 1/14 : FROM ghcr.io/foundry-rs/foundry
 ---> 479d39683929
Step 2/14 : RUN apk update ; apk add --no-cache --allow-untrusted ca-certificates curl bash git jq
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in b20922adacd0
exec /bin/sh: exec format error
The command '/bin/sh -c apk update ; apk add --no-cache --allow-untrusted ca-certificates curl bash git jq' returned a non-zero code: 1
Error running build for cerc/go-ethereum-foundry
FATAL Error: container build failed and --continue-on-error not set, exiting
```

**Comment by dboreham** [comment]
Note that the foundry Dockerfile uses directives only available in the BuildKit version of Docker builder, which in turn seems hard to enable for the typical user. These directives are (of course...) not backwards compatible. For now in testing I just removed them: https://github.com/foundry-rs/foundry/blob/master/Dockerfile#L18

**Comment by dboreham** [comment]
It also depends on this: https://github.com/Docker-Hub-frolvlad/docker-alpine-glibc which yet again has no ARM64 build.

**Comment by dboreham** [comment]
Really the problem here is that foundry folks were trying to build a super-small Docker image and therefore used some tricks with Alpine + glibc. If we just build the image on Ubuntu I think everything would be fine. We'd use our own Dockerfile for that.

**Comment by zramsay** [comment]
not sure if it's [this commit](https://github.com/cerc-io/stack-orchestrator/commit/14e57abfbfa2d137f910d46080569773ebfa8456)
but i'm currently getting this error:
```
Successfully tagged cerc/go-ethereum:local
Building: cerc/go-ethereum-foundry
Sending build context to Docker daemon  22.02kB
Step 1/14 : FROM foundry-rs/foundry:local
pull access denied for foundry-rs/foundry, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

on fresh Linux with:
```
 laconic-so version
Version: v1.0.18-db57756
```

having run:
```
laconic-so --stack erc20 setup-repositories
laconic-so --stack erc20 build-containers
```

**Comment by dboreham** [comment]
Reverted the local foundry image since it proved impossible to build locally without extensive changes.
https://github.com/cerc-io/stack-orchestrator/pull/172

**Comment by zramsay** [comment]
fixed, thanks

**Comment by dboreham** [comment]
Resurrecting this one because I found that foundry project is currently shipping a broken container.

**Comment by dboreham** [comment]
Fixed in : https://github.com/cerc-io/stack-orchestrator/pull/214 (still won't build for ARM though)
