### ISSUE TITLE
Quickstart Tutorial: Failing `deploy-system up` due to missing docker-compose-lighthouse.yml.

### ISSUE THREAD

**Issue by rickmanelius** [cerc-io/stack-orchestrator#177]
Background
* [Following instructions](http://docs-staging.laconic.com/docs/tutorials/quick-start/) to download and use `laconic-so` v1.10.19 
* Setup and build stages succeed. Standing up fails.
* Error observed 

```
➜  stack-orchestrator git:(main) ./laconic-so deploy-system up
stat /Users/rickmanelius/.shiv/laconic-so_1f20cd82c136cacd0f0ca19b7db9d3686136515885cd9da8839e8d6ff26c20fb/site-packages/app/data/compose/docker-compose-lighthouse.yml: no such file or directory
Traceback (most recent call last):
```

**Comment by dboreham** [comment]
This command : `./laconic-so deploy-system up` doesn't appear anywhere in the tutorial, so I'm a bit confused.
What command were you running?

**Comment by rickmanelius** [comment]
Thanks for catching that. Yes, you're right ( I copied a later line at the summary, and that didn't include the extra parameters)

```
deployed these images as services that know about each other: laconic-so deploy-system up
```

Now I get a different error / blocker

```
 ➜  stack-orchestrator git:(main) ./laconic-so --stack erc20deploy-system up
Usage: python -m laconic-so [OPTIONS] COMMAND [ARGS]...
Try 'python -m laconic-so -h' for help.
```

Prepending `python -m` or `python3 -m` as suggested doesn't seem to fix.

I had this working as of https://www.notion.so/Testing-Stack-Orchestrator-macOS-369eb605185144ecabadbc0f1c2e016f#8b8d955cbff94a63984e411eaa522ab7 (last edit January 10th). And I don't believe I changed my python or docker setup then. So I've tried finding older versions of the README.md or quickstart, but stuck here at the moment.

**Comment by rickmanelius** [comment]
Before you respond. Going down other paths https://github.com/cerc-io/stack-orchestrator/tree/main/app/data/stacks/erc20. If I can't unblock myself after an hour, I'll report my findings from this other page.

**Comment by dboreham** [comment]
Fixes for the doc: https://github.com/LaconicNetwork/docs.laconic.com/pull/107

**Comment by dboreham** [comment]
Try this: `./laconic-so --stack erc20 deploy-system up`

There was a typo in the tutorial.

**Comment by rickmanelius** [comment]
@dboreham Thanks! That fixed it. Also found another path forward [here](https://github.com/cerc-io/stack-orchestrator/tree/main/app/data/stacks/erc20) (where you specify everything with includes). But I like your version better. Closing

**Comment by dboreham** [comment]
Thanks, I fixed that other doc to use the newer stack syntax.
