### ISSUE TITLE
Howto Modify The ERC-721 Stack To Connect To an Ethereum Mainnet Full Node?

### ISSUE THREAD

**Issue by rickmanelius** [cerc-io/stack-orchestrator#179]
### Where I Am: 
I can successfully standup the `laconic-so` [erc20](https://github.com/cerc-io/stack-orchestrator/tree/main/app/data/stacks/erc20) and erc721 stacks as well as step through the demos. 

### What I'd Like to Do
Now I want to take a bigger leap and start standing up watchers against Eth L1 mainnet to observe an active contract (e.g. [VV Checks](https://etherscan.io/address/0x34eebee6942d8def3c125458d1a86e0a897fd6f9)). This would be helpful for generating watchers locally that we can build local web apps against.

### Where I'm Not Sure What To Do Next
I've reviewed `stack-orchestrator/app/data/*` folders and it looks like there are a few places to change around the configuration and Docker build instructions to achieve this, but I'm not confident I'd figure out all of the changes on my own. I'm not needing (nor wanting) to back-fill data. In an ideal situation, I could...

1. Clone this repo and clone the erc721 stack to erc721-checks
2. Change configurations (e.g. chainID, full-node sync, etc)
3. Setup repos, build, and stand-up stack
4. Build/initialize the VV Checks watcher using generic ERC721 watcher
5. Test GraphQL queries for all transfer events moving forward

I'm happy to hop on a call and record a walk-through, document the steps, and submit a PR to our docs with these instructions.

And if I'm going about this the wrong way, I'm happy to be steered into another direction to achieve a similar outcome.

**Comment by dboreham** [comment]
The [back-end services](https://github.com/cerc-io/stack-orchestrator/blob/main/app/data/stacks/erc20/stack.yml#L14) that you get deployed by stack orchestrator in the demo scenario need to be deployed for mainnet. That's not something we have automated at present so would need to be done manually. The fact that it involves large amounts of persisted data (TB) is really what makes it non-trivial.

**Comment by AFDudley** [comment]
@rickmanelius I think it would be extremely helpful for you to have a full understanding of what an Ethereum smart contract is, this would help explain why backfilling data is a hard requirement that requires TBs of space, as David mentioned. I'd be happy to help you get that deeper level of understanding.

**Comment by rickmanelius** [comment]
Hi @AFDudley. In this instance, I specified not wanting historical data (" I'm not needing (nor wanting) to back-fill data.") in an attempt to avoid this requirement (e.g. only watching for all future blocks).

I recognize this might not avoid the difficulty/challenges altogether. But for local dev purposes, it would be helpful to be able to be able connect watchers to mainnet versus having to scaffold test data.

As for Solidity experience, I did take about 20 hours over the past two weeks going through the a few series that Lance suggested and using Remix/Hardhat to level of up my usage/testing of them. I'm aware I still have gaps in my knowledge base, but I'm more than happy to take you up on the offer to keep getting stronger on that front.

**Comment by dboreham** [comment]
Understood but you need the full head state in geth and ipld-db and that's still TB.

**Comment by rickmanelius** [comment]
@dboreham Ok great. Thank you for that, and I apologize for not understanding the weight of what is still needed just for the ability to go forward.

Assuming someone like me wanted to go forward on this and had a local 20TB external hard drive, would that be sufficient as long as I had the DB snapshots to manually import/connect to?

**Comment by rickmanelius** [comment]
BTW. Given this is now a non-trivial lift/modification, I will pause on this because it doesn't sound like a worthwhile usage of time. My naive hope was it was something I could swap out, but as @AFDudley pointed out, I had a glaring miss on requirements.

If we have other inbound requests for this, perhaps then it'll make sense to document and provide instructions for this.

**Comment by AFDudley** [comment]
>it would be helpful to be able to be able connect watchers to mainnet versus having to scaffold test data.

Yes, it would be helpful. Also, sort of amazing that in the 5 years we've been working on this project you're the first person to think of it.
