### ISSUE TITLE
Support the mobymask extension

### ISSUE THREAD

**Issue by zramsay** [cerc-io/stack-orchestrator#221]
https://github.com/lxdao-official/mobymask-extension

**Comment by dboreham** [comment]
Hm:

```
"name": "chatgpt-anywhere-extension"
```

**Comment by ashwinphatak** [comment]
@zramsay , the following has been tested on Linux and Mac M1. Can you try and run through the demo and see if it works for you?

* https://github.com/cerc-io/stack-orchestrator/blob/main/app/data/stacks/mobymask-v2/README.md
* https://github.com/cerc-io/stack-orchestrator/blob/main/app/data/stacks/mobymask-v2/demo.md

**Comment by zramsay** [comment]
onit :)

**Comment by nikugogoi** [comment]
> https://github.com/lxdao-official/mobymask-extension

Tried out the extension locally. There is no functionality of reporting phishers in MobyMask
Also took a brief look at the code. Couldn't find anything related to reporting phishers or endorsing members.

**Comment by zramsay** [comment]
thanks. I think it's not really in scope right now so let's call this a wontfix for the time being
