### ISSUE TITLE
either setup-repositories should be a little smarter or fine tune the `--branches-file` or `--pull` options

### ISSUE THREAD

**Issue by zramsay** [cerc-io/stack-orchestrator#242]
e.g., for the MM instructions, there is a clunky workaround that involves manually going into each repo and running `git checkout vSomeVersion` for 5 repos.

Either a the branch could be specified in a `stack` or we implement some combination of #142 and/or #209

Low priority IMO, just tracking some thoughts

**Comment by zramsay** [comment]
> do we really need all this branch switching? Why not merge the necessary code onto a branch and set that as the default?
IMO yes because we're always going to be to merging work into SO that is still a WIP across >1 repo. The alternative is that some cool stack we want in the latest SO release blocks indefinitely because 1/n (or more) repos are awaiting async merges.

**Comment by dboreham** [comment]
I'm more debating the frequency at which we do this. I would argue if someone made a bunch of code and now thinks it is ready for outsiders to test, then it should be merged and not still on a feature branch.

**Comment by zramsay** [comment]
I have so many thoughts...I suspect more frequently than we think yet totally agree wrt to `it should be merged and not still on a feature branch`

**Comment by dboreham** [comment]
I think we should pause before adding more git management functionality to this product.
Complex branch management scenarios, CI jobs run on a mix of different branches, developer workflow, I think should be out of scope. Those situations can be handled by other tools, and stack-orchestrator used only to build and deploy containers.

I see the git functionality in stack orchestrator to be there as a convenience for users aiming to spin up something from "stock" code from a set of repositories.

**Comment by zramsay** [comment]
closing in favour of #260
