### ISSUE TITLE
In binary release `.env` file didn't mount in mobymask-v2-watcher container

### ISSUE THREAD

**Issue by nikugogoi** [cerc-io/stack-orchestrator#247]
A `.env` file needs to be mounted in [mobymask-v2-watcher container](https://github.com/cerc-io/stack-orchestrator/blob/v1.0.30/app/data/compose/docker-compose-watcher-mobymask-v2.yml#L33). The setup works properly in development.
* Expected: Will work the same way in released binary
* Actual: The file was not mounted in the [released binary](https://github.com/cerc-io/stack-orchestrator/releases/tag/v1.0.30).

[Workaround](https://github.com/cerc-io/stack-orchestrator/pull/226/commits/7eb6fe6d99afa570e99dfe9d730d5ddf8db7f745): Renamed file `.env` to `peer.env`

**Comment by dboreham** [comment]
I've always considered `.env` files as an antipattern. Can we live without one here?

**Comment by nikugogoi** [comment]
Yes we can avoid using `.env` files.
Closing issue since workaround to rename `.env` file is already implemented.
