### ISSUE TITLE
Error thrown in `setup-repositories` command if local repo is already checked out to different version

### ISSUE THREAD

**Issue by nikugogoi** [cerc-io/stack-orchestrator#257]
In [MobyMask v2 watcher stack](https://github.com/cerc-io/stack-orchestrator/tree/v1.0.32/app/data/stacks/mobymask-v2) we need to [check out to working version or branch](https://github.com/cerc-io/stack-orchestrator/blob/v1.0.32/app/data/stacks/mobymask-v2/README.md?plain=1#L16) in the cloned repos.

If `setup-repositories` command is run again after repos are checked out to a different version:
* Expected: It should not throw any error
* Actual: An error is thrown
    ```
    TypeError: HEAD is a detached symbolic reference as it points to '998e4f59173648ffbaed8d068b8cf57e28dfb3ad'
    ```

**Comment by dboreham** [comment]
Don't run setup-repositories if manual branch management is done.

**Comment by zramsay** [comment]
see #260. FWIW I've been using a simple script after `laconic-so --stack mobymask-v2 setup-repositories` to check out all the correct branches.
