### ISSUE TITLE
Add external config environment variable file for stack deploy

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#280]
Currently all deploy environment variables are either defined in the compose files or fetched from a static file inside the stack orchestrator package. Add the capability to load environment variables from an arbitrary file e.g. with `laconic-so --stack foo --env-file /my/file/name.env deploy up`

**Comment by dboreham** [comment]
Some implementation notes:

Pass the env file name, if present here: https://github.com/cerc-io/stack-orchestrator/blob/main/app/deploy_system.py#L54 in the  `compose_env_file` parameter documented [here](https://gabrieldemarmiesse.github.io/python-on-whales/docker_client/).

Parsing `--env-file` from the command line may be tricky -- I don't think we have any `--foo` for the subcommands yet, but memory is hazy. That functionality is implemented in [click](https://click.palletsprojects.com/en/8.1.x/).

**Comment by prathamesh0** [comment]
@dboreham Have added an option (`--env-file`) to pass env file for the `deploy` command in #304

An example usage would look like this:
```bash
laconic-so --stack fixturenet-optimism deploy --include fixturenet-optimism --env-file ./my-env.env up
```
As can be seen in the PR [changes](https://github.com/cerc-io/stack-orchestrator/pull/304/files#diff-049386f3d017d80afa53ccabc6856fa8ce28127cd4407e75b6e42a6797eac4ceR52), the `env-file` is not made part of the `cluster_context` unlike other deploy options. We discussed this, but it wasn't clear whether we should somehow accommodate the `env-file` value in a cluster's context? What do you think?

**Comment by dboreham** [comment]
> @dboreham Have added an option (`--env-file`) to pass env file for the `deploy` command in #304
> 
> An example usage would look like this:
> 
> ```shell
> laconic-so --stack fixturenet-optimism deploy --include fixturenet-optimism --env-file ./my-env.env up
> ```
> 
> As can be seen in the PR [changes](https://github.com/cerc-io/stack-orchestrator/pull/304/files#diff-049386f3d017d80afa53ccabc6856fa8ce28127cd4407e75b6e42a6797eac4ceR52), the `env-file` is not made part of the `cluster_context` unlike other deploy options. We discussed this, but it wasn't clear whether we should somehow accommodate the `env-file` value in a cluster's context. What do you think?

I think it should probably be in the cluster context so these envs are available to orchestration scripts, and execs and so on. I will file a bug for this.

**Comment by dboreham** [comment]
Feature has been implemented.
