### ISSUE TITLE
Support container forced rebuild

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#319]
Docker is oh so clever about not needing to build image layers. But not quite clever enough. 
So often it believes something doesn't need to be rebuilt when yeah it does.

Add an option to force rebuild (which I seem to remember is called `--no-cache` or something equally confusing by docker).

See also : https://github.com/cerc-io/stack-orchestrator/issues/317

**Comment by zramsay** [comment]
yep, `--no-cache`, I've been breaking the 4th wall today adding it in various places

**Comment by dboreham** [comment]
Done
