### ISSUE TITLE
geth container binary inconsistent with command options

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#454]
Testing mobymask-v2 stack I see this in the fixturenet-eth-geth container:

```
Incorrect Usage. flag provided but not defined: -log.vmodule

NAME:
   geth - the go-ethereum command line interface

USAGE:
   geth [global options] command [command options] [arguments...]

VERSION:
   1.11.5-statediff-4.3.9-alpha-4e7a42eb-20230406
```

**Comment by dboreham** [comment]
This may have crept in with some plugeth changes, unnoticed because we don't run the fixturenet-eth test on every PR.

It looks like this commit : https://github.com/cerc-io/stack-orchestrator/commit/809889f9f03c843a56b7cf1eb76767dbf0e913f8#diff-e397b8ae6dcabdce76c66636365b2f565020818ba4d2d55591d8259feefb16e3R133 introduced a command line option that seems to be invalid for regular geth (but probably ok for plugeth).

The result is that the geth fixturenet doesn't work.

**Comment by telackey** [comment]
This is odd, I'm using geth fixturenet.

**Comment by telackey** [comment]
```
~/cerc/go-ethereum  v1.11.6-statediff-v5 ✗= ❯ make geth
env GO111MODULE=on go run build/ci.go install ./cmd/geth
>>> /home/telackey/opt/go1.20.5/bin/go build -ldflags "-X github.com/ethereum/go-ethereum/internal/version.gitCommit=1b72d2f737a031fd6617aa0954a6a5b96a487426 -X github.com/ethereum/go-ethereum/internal/version.gitDate=20230718 -extldflags '-Wl,-z,stack-size=0x800000'" -tags urfave_cli_no_docs -trimpath -v -o /home/telackey/cerc/go-ethereum/build/bin/geth ./cmd/geth
Done building.
Run "./build/bin/geth" to launch geth.
~/cerc/go-ethereum  v1.11.6-statediff-v5 ✗= ❯ build/bin/geth --help | grep -i vmodule
    --log.vmodule value
```

**Comment by telackey** [comment]
I actually finally switched it, because for awhile geth had been _warning_ that `--vmodule` was deprecated and we needed to switch to `--log.vmodule`.

**Comment by dboreham** [comment]
This seems significant:

```
v1.11.6
```

**Comment by dboreham** [comment]
It looks like the problem is that our go-ethereum repo changes default branch.
That is problematic if you have an existing cloned tree because there's no way to know from the client side that the default branch changed. My setup therefore continued building old code, even though I'd told it to pull from git and force a container rebuild.

**Comment by dboreham** [comment]
Closing as machine-specific.
