### ISSUE TITLE
Support mainnet eth deployment

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#457]

**Comment by AFDudley** [comment]
everything seems to be working but I have some odd permissions and I'm wondering if it's my configuration or expected behavior:

> rix@night2:~/code/laconic-so/mainnet-eth-deployment/data/mainnet-eth/geth$ ls -lah
>total 3.5K
>drwxr-xr-x 4 rix  root 5 Jul 25 13:24 .
>drwxr-xr-x 5 rix  root 5 Jul 25 13:08 ..
>drwx------ 4 root root 7 Jul 25 13:24 geth
>srw------- 1 root root 0 Jul 25 13:24 geth.ipc
>drwx------ 2 root root 2 Jul 25 13:11 keystore

**Comment by dboreham** [comment]
It's a docker weird thing related to bind mounts. We have a trick to avoid the root ownership but I haven't implemented it yet in this stack.

**Comment by dboreham** [comment]
Done
