### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#5]
Orchestrator needs at least some sort of CI test to ensure it doesn't become inadvertently broken.

**Comment by dboreham** [comment]
Initial step: add a release script that pushes to github releases

**Comment by zramsay** [comment]
concur on that first step. If they can be tagged "latest" (at least for now while rapidly iterating SO) that would help a lot with not having to consistently update docs to the latest version. e.g., 
```
 curl -L https://github.com/cerc-io/stack-orchestrator/releases/download/latest/laconic-so
```
vs.
```
 curl -L https://github.com/cerc-io/stack-orchestrator/releases/download/v1.0.3-alpha/laconic-so
 ```

**Comment by dboreham** [comment]
It looks like github computes "latest" based on release timestamps? All our published releases were marked as prerelease which excludes them from the scope of latest. I changed the most recent release to be "not prerelease" and it magically made it the latest.

**Comment by zramsay** [comment]
I can confirm this works, but with this URL:
 `curl -L https://github.com/cerc-io/stack-orchestrator/releases/latest/download/laconic-so` (had to swap latest & download)

**Comment by dboreham** [comment]
We now have CI: https://git.vdb.to/cerc-io/stack-orchestrator/actions
