### ISSUE TITLE
Error on trying to deploy `fixturenet-laconic-loaded` stack

### ISSUE THREAD

**Issue by nikugogoi** [cerc-io/stack-orchestrator#518]
An error is thrown in `build-npms` command when following the [steps for deploying](https://github.com/cerc-io/stack-orchestrator/blob/main/app/data/stacks/fixturenet-laconic-loaded/README.md) `fixturenet-laconic-loaded` stack
```bash
$ laconic-so build-npms --include laconic-sdk,laconic-registry-cli
Building npm package: laconic-sdk
Fixing up dependencies in scope @cerc-io
Fixing up dependencies in scope @lirewine
Fixing up dependencies in scope @muknsys
Running build
Build and publish @cerc-io/laconic-sdk version 0.1.6
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
error Could not write file "/workspace/yarn-error.log": "EACCES: permission denied, open '/workspace/yarn-error.log'"
error An unexpected error occurred: "EACCES: permission denied, mkdir '/workspace/node_modules'".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error executing build for laconic-sdk in container:
 The docker command executed was `/usr/local/bin/docker container run --add-host gitea.local:host-gateway --env CERC_NPM_AUTH_TOKEN=474b5fe92c287742b126c38f2f041143559bb2ca --env LACONIC_HOSTED_CONFIG_FILE=config-hosted.yml --interactive --tty --rm --user 1000:1000 --volume /home/nabarun/cerc/build-trees/laconic-sdk:/workspace cerc/builder-js:local sh -c cd /workspace && build-npm-package-local-dependencies.sh http://gitea.local:3000/api/packages/cerc-io/npm/`.
It returned with code 1
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr can be found above the stacktrace (it wasn't captured).
FATAL Error: build failed and --continue-on-error not set, exiting
```
Had also checked the steps in [build-support stack readme](https://github.com/cerc-io/stack-orchestrator/blob/main/app/data/stacks/build-support/README.md)

**Comment by dboreham** [comment]
Hi, can you try rebuilding the cerc/builder-js container?

```
laconic-so build-containers --include cerc/builder-js --force-rebuild
```

**Comment by zramsay** [comment]
David's suggestion is likely correct  - I couldn't reproduce or haven't see that error. That said, the gitea/build-npms/laconicd/console "vertical" is a bit confusing. #519 helps; [this doc](https://github.com/cerc-io/stack-orchestrator/blob/main/docs/laconicd-fixturenet.md) omits the `build-npms` step by using the published packages in our gitea.

**Comment by dboreham** [comment]
btw also, it isn't necessary to build the npms if all you need is to spin up the stack -- building the containers is enough because the builds will pull the npm packages from our npm repository.

**Comment by zramsay** [comment]
https://github.com/cerc-io/stack-orchestrator/blob/main/docs/laconicd-with-console.md works reliably
