### ISSUE TITLE
Current shiv release is broken

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#69]
```
root# ./laconic-so --verbose build-containers
Dev Root is: /root/cerc
Containers: ['cerc/test-contract', 'cerc/eth-statediff-fill-service', 'cerc/eth-statediff-service', 'cerc/go-ethereum', 'cerc/go-ethereum-foundry', 'cerc/lighthouse', 'cerc/ipld-eth-db', 'cerc/ipld-eth-beacon-db', 'cerc/ipld-eth-beacon-indexer', 'cerc/ipld-eth-server', 'cerc/laconicd', 'cerc/laconic-cns-cli', 'cerc/fixturenet-eth-geth', 'cerc/fixturenet-eth-lighthouse', 'cerc/watcher-mobymask', 'cerc/test-container']
Building: cerc/test-contract
Script: container-build/cerc-test-contract/build.sh
Error, script: container-build/cerc-test-contract/build.sh doesn't exist
```

**Comment by dboreham** [comment]
Problem is that the directories `./container-build` and `./compose` and `./stacks` are not getting packaged.

**Comment by dboreham** [comment]
Probably we should use this instead of pkg_resources: https://docs.python.org/3.8/library/importlib.html?highlight=importlib#module-importlib.resources

**Comment by dboreham** [comment]
Fix wip: https://github.com/cerc-io/stack-orchestrator/pull/99

**Comment by dboreham** [comment]
Shiv package should work now : https://github.com/cerc-io/stack-orchestrator/pull/99

I will cut a new "binary" release to github when this has been tested properly.

**Comment by zramsay** [comment]
Sweet, will test today.

**Comment by zramsay** [comment]
I'm not convinced this is fixed b/c I ran into the same error with v1.0.4-alpha ... then when trying to reproduce, ran into some other errors (that are already fixed). Working on clear steps to reproduce.

**Comment by dboreham** [comment]
Also a bit odd that you had to exclude `vulcanize/ops` earlier because that was removed form the container list a while back. Possibly somehow you're running old code?

**Comment by zramsay** [comment]
you are right, shasum matched the v1.0.3 binary 🤦
