### ISSUE TITLE
Rename `db` to `ipld-eth-db`

### ISSUE THREAD

**Issue by zramsay** [cerc-io/stack-orchestrator#71]
If running `deploy-system` with e.g., `--include ipld-eth-server` but not `db` the error says to run `ipld-eth-db` but it's not immediately obvious you need to run `--include db` rather than the assumed `--include ipld-eth-db` (former works, latter doesn't)

 AFAICT this is just renaming [this file](https://github.com/cerc-io/stack-orchestrator/blob/main/compose/docker-compose-db.yml)

**Comment by dboreham** [comment]
Fixed: https://github.com/cerc-io/stack-orchestrator/pull/97
