### ISSUE TITLE
shiv install didn't work

### ISSUE THREAD

**Issue by rickmanelius** [cerc-io/stack-orchestrator#76]
I wasn't able to get `curl` to work (even when using `--output laconic-so`. `wget` worked like a charm.

**Comment by rickmanelius** [comment]
Better yet would be any script that would run to drop this into /usr/local/bin on the key distros.

**Comment by dboreham** [comment]
I'm not sure how to interpret this. Did you see an error from curl?

**Comment by zramsay** [comment]
+ 1
I encountered this too and just assumed I was doing something wrong. No error from curl. No output from running the binary
![Screen Shot 2022-12-21 at 05 41 02](https://user-images.githubusercontent.com/8304391/208886249-563c0058-ca05-4333-ae07-509c08538706.png)

**Comment by dboreham** [comment]
I doubt this is anything to do with curl vs wget.

**Comment by rickmanelius** [comment]
@dboreham I figured it out.

This `curl https://github.com/cerc-io/stack-orchestrator/releases/download/v1.0.3-alpha/laconic-so`

Needs to have a `-L` flag. Without it, curl returns a 0 byte file.

@zramsay I suggest the following change to README.md

`curl -L https://github.com/cerc-io/stack-orchestrator/releases/download/v1.0.3-alpha/laconic-so -o laconic-so`

**Comment by dboreham** [comment]
Bah. Github changed the asset hosting since I tried this. It redirects to a generated URL now, so `curl` needs `-L` .

**Comment by dboreham** [comment]
README fixed.
