### ISSUE TITLE
AMD64 images on macOS w/M1 hardware

### ISSUE THREAD

**Issue by rickmanelius** [cerc-io/stack-orchestrator#85]
Basically, I get the following warning in the Docker Desktop Dashboard.

<img width="510" alt="Screenshot 2022-12-29 at 9 12 56 PM" src="https://user-images.githubusercontent.com/913096/210030685-f8849a92-e640-4547-898e-6f172ca647fc.png">

Seems similar to https://stackoverflow.com/questions/70765522/docker-amd64-warning-on-apple-m1-computer

I imagine we may need to pass a flag for different architectures to target different base docker images.

**Comment by dboreham** [comment]
This is a common issue with 3rd party container images -- the project hasn't published an aarm64 image so Docker pulled the amd64 one and ran it under emulation.

**Comment by dboreham** [comment]
Closing as dup of : https://github.com/cerc-io/stack-orchestrator/issues/2
